<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <style>body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    header {
        background-color: #333;
        color: #fff;
        padding: 10px 0;
    }
    
    nav ul {
        list-style: none;
        display: flex;
        justify-content: center;
        margin: 0;
        padding: 0;
    }
    
    nav ul li {
        margin: 0 15px;
    }
    
    nav ul li a {
        color: #fff;
        text-decoration: none;
    }
    
    .hero {
        background-color: #f4f4f4;
        text-align: center;
        padding: 50px 0;
    }
    
    section {
        padding: 20px;
        text-align: center;
    }
    
    footer {
        background-color: #333;
        color: #fff;
        text-align: center;
        padding: 10px 0;
        position: fixed;
        width: 100%;
        bottom: 0;
    }
    </style>
    <header>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <section id="home" class="hero">
        <h1>Welcome to My Website</h1>
        <p>This is a simple hero section with a welcome message.</p>
    </section>
    <section id="about">
        <h2>About Us</h2>
        <p>We are a company that provides excellent services to our clients.</p>
    </section>
    <section id="services">
        <h2>Our Services</h2>
        <p>We offer a variety of services to meet your needs.</p>
    </section>
    <section id="contact">
        <h2>Contact Us</h2>
        <form id="contactForm">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
            <label for="message">Message:</label>
            <textarea id="message" name="message" required></textarea>
            <button type="submit">Submit</button>
        </form>
    </section>
    <footer>
        <p>© 2024 My Website. All rights reserved.</p>
    </footer>
    <script src="script.js"></script>
    <script src="ww.js"></script>
</body>
</html>
